### PR TITLE
QbUtil: consistent orientation + unix support in shader paths

### PR DESCRIPTION
**Pull request by chrmoritz**
This PR changes the code for loading compressed `.qb` files to make it consistent with the model orientation changes introduced in 94dce53

### CODE REVIEW

**Comment by chrmoritz** [comment]
added a fix for shader paths on unix.
At the moment you are using a absolute path without the leading `/`, which is interpreted as a relative path and throws a java.nio.file.NoSuchFileException on loading shaders.
It looks like a leading slash before Volume names is causing no issues on Windows so this change should make it cross platform compatible.
But I would recommend lowering the opengl version requirement further if possible.

**Comment by honestabelink** [comment]
I am a bit confused with all these orientation changes... _could be cause it's late_

Is this the proper way to read the .qb's, or was your change flipping the x axis a response to my latest 
commits?

EDIT:
Ok I see now... _I guess it is too late_

also 
`tz = model.zAxisOrientation == 0 ? z : (int) def.size.z - z - 1;`

this seems to show me that StoneVox has front/back mixed up, is this the case.

shader path changes are good, I will lower the opengl requirement it is just a simple change to the shaders and a little code, good recommendation.

**Comment by chrmoritz** [comment]
The first commit which change the import behavior to not mirror the axis was only a response to your change in 94dce53 (I couldn't base my first PR on it because it wasn't pushed to the repo at the time I've created it).

`tz = model.zAxisOrientation == 0 ? z : (int) def.size.z - z - 1;`
This handles an option in the `.qb` file format (1 byte in the metadata section), where you can specify if the z axis should be left handed (0) or right handed (1). It just assumes that we want to have the z axis left handed (the most common way). If the option is set to left handed it just uses z as normal, but if it finds a right handed option it mirrors z to be left haded.

It would be good to lower the OpenGl version to 3.x because 4.0 isn't supported on a geforce 300- and in the open linux mesa drivers and OS X supports atm only 4.1 (4.2+ is partly unsupported).

BTW: Don't think this axis orientation stuff is confusing before you have started implementing different voxel formats. For example Magica Voxel things it has to interchange the y and z axis (so coords are stored in x, z, y order). The funny part is that its qb importer handles this interchange correctly but the exporter not. If you import a qb file in Magica Voxel and export it again to .qb you will have a rotated and mirrored model.

**Comment by honestabelink** [comment]
Thanks for clearing things up,

`tz = model.zAxisOrientation == 0 ? z : (int) def.size.z - z - 1;`

"this seems to show me that StoneVox has front/back mixed up, is this the case."

What I meant was was when I load a `.qb` both the front and back faces seem to be positioned incorrectly now. Which makes sense if you look at the `QbMatrixSide`'s code for setting the vertexes.

The back face of a voxel vertexes are positioned in the +z. While,
the front/forward face of a voxel vertexes are positioned in the -z.

This is incorrect. It should be the other way around.

Also loaded `.qb`'s now face away from the "camera", further confirming this to me.

You seem to have exposed quite the underlying bug in my program... thanks

Please correct me if you think I am wrong.

**Comment by chrmoritz** [comment]
The change should be independent of vertex position, so it should be a bug in QbMatrixSide and you were the fist one who has exposed it by 94dce53.

> Also loaded .qb's now face away from the "camera", further confirming this to me.

As I said above, different programs are defining the axis and their orientation in different way. It might be worth it to mirror the x axis again for both compressed and uncompressed.

**Pull request merged**
